
package com.mycompany.fitlifegym_presentacion;

import com.mycompany.fitlifegym_dtos.CategoriaDTO;
import com.mycompany.fitlifegym_dtos.EstadoReporteDTO;
import com.mycompany.fitlifegym_dtos.FiltrosConsultaHistorialReportesNegocioDTO;
import com.mycompany.fitlifegym_negocio.NegocioException;
import java.time.LocalDate;
import java.util.List;
import javax.swing.JOptionPane;

/**
 *
 * @author Julian
 */
public class BuscadorRegistrosReportesClientesFORM extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(BuscadorRegistrosReportesClientesFORM.class.getName());
    private NavegacionForms navegacionForms;
    private ControlSubsistemaQuejasSugerencias control;
    
    /**
     * Creates new form BuscadorRegistrosReportesClientesFORM
     * @param navegacionForms
     * @param control
     */
    public BuscadorRegistrosReportesClientesFORM(NavegacionForms navegacionForms, ControlSubsistemaQuejasSugerencias control) {
        initComponents();
        this.setLocationRelativeTo(null);
        this.navegacionForms = navegacionForms;
        this.control = control;
        llenarComboCategorias();
        llenarComboEstados();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        lblTitulo = new javax.swing.JLabel();
        btnVolcer = new javax.swing.JButton();
        lblFiltroNombre = new javax.swing.JLabel();
        lblFiltroEstado = new javax.swing.JLabel();
        txtFiltroNombre1 = new javax.swing.JTextField();
        comboCategorias = new javax.swing.JComboBox<>();
        lblFiltroCategoria = new javax.swing.JLabel();
        lblFechaDesde = new javax.swing.JLabel();
        lblFechaHasta = new javax.swing.JLabel();
        comboEstados1 = new javax.swing.JComboBox<>();
        btnBuscar = new javax.swing.JButton();
        btnRestablecer = new javax.swing.JButton();
        selectorFechaHasta = new com.github.lgooddatepicker.components.DatePicker();
        selectorFechaDesde = new com.github.lgooddatepicker.components.DatePicker();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(102, 102, 102));

        jPanel3.setBackground(new java.awt.Color(51, 51, 51));

        lblTitulo.setText("GymFit- Buscador Registros Reportes");
        lblTitulo.setFont(new java.awt.Font("Segoe UI", 3, 26)); // NOI18N
        lblTitulo.setForeground(new java.awt.Color(255, 255, 255));

        btnVolcer.setText("Volver");
        btnVolcer.setBackground(new java.awt.Color(0, 0, 0));
        btnVolcer.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnVolcer.setForeground(new java.awt.Color(255, 255, 255));
        btnVolcer.addActionListener(this::btnVolcerActionPerformed);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnVolcer)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 46, Short.MAX_VALUE)
                .addComponent(lblTitulo)
                .addGap(122, 122, 122))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblTitulo)
                    .addComponent(btnVolcer))
                .addGap(0, 6, Short.MAX_VALUE))
        );

        lblFiltroNombre.setText("Cliente (Nombre):");
        lblFiltroNombre.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        lblFiltroNombre.setForeground(new java.awt.Color(255, 255, 255));

        lblFiltroEstado.setText("Estado: ");
        lblFiltroEstado.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        lblFiltroEstado.setForeground(new java.awt.Color(255, 255, 255));

        txtFiltroNombre1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtFiltroNombre1.setBackground(new java.awt.Color(255, 255, 255));
        txtFiltroNombre1.setForeground(new java.awt.Color(0, 0, 0));

        comboCategorias.setBackground(new java.awt.Color(255, 255, 255));
        comboCategorias.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        comboCategorias.setForeground(new java.awt.Color(0, 0, 0));

        lblFiltroCategoria.setText("Categoría:");
        lblFiltroCategoria.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        lblFiltroCategoria.setForeground(new java.awt.Color(255, 255, 255));

        lblFechaDesde.setText("Fecha Desde:");
        lblFechaDesde.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        lblFechaDesde.setForeground(new java.awt.Color(255, 255, 255));

        lblFechaHasta.setText("Fecha Hasta: ");
        lblFechaHasta.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        lblFechaHasta.setForeground(new java.awt.Color(255, 255, 255));

        comboEstados1.setBackground(new java.awt.Color(255, 255, 255));
        comboEstados1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        comboEstados1.setForeground(new java.awt.Color(0, 0, 0));

        btnBuscar.setText("Buscar");
        btnBuscar.setBackground(new java.awt.Color(0, 0, 0));
        btnBuscar.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnBuscar.setForeground(new java.awt.Color(255, 255, 255));
        btnBuscar.addActionListener(this::btnBuscarActionPerformed);

        btnRestablecer.setText("Restablecer Filtros");
        btnRestablecer.setBackground(new java.awt.Color(0, 0, 0));
        btnRestablecer.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnRestablecer.setForeground(new java.awt.Color(255, 255, 255));
        btnRestablecer.addActionListener(this::btnRestablecerActionPerformed);

        selectorFechaHasta.setBackground(new java.awt.Color(41, 41, 41));

        selectorFechaDesde.setBackground(new java.awt.Color(41, 41, 41));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(161, 161, 161)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lblFechaHasta)
                            .addComponent(lblFiltroEstado)
                            .addComponent(lblFiltroNombre)
                            .addComponent(lblFiltroCategoria)
                            .addComponent(lblFechaDesde))
                        .addGap(60, 60, 60))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(btnBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnRestablecer, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(txtFiltroNombre1, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(comboEstados1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 197, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(comboCategorias, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 197, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(selectorFechaHasta, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 197, Short.MAX_VALUE)
                        .addComponent(selectorFechaDesde, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblFiltroNombre)
                    .addComponent(txtFiltroNombre1, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblFiltroEstado)
                    .addComponent(comboEstados1, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblFiltroCategoria)
                    .addComponent(comboCategorias, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addComponent(lblFechaDesde)
                        .addGap(30, 30, 30))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(selectorFechaDesde, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblFechaHasta)
                    .addComponent(selectorFechaHasta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 54, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnRestablecer, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(14, 14, 14))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarActionPerformed
        try {
            FiltrosConsultaHistorialReportesNegocioDTO filtros = filtros();
            control.consultarTodosLosReportesFiltrados(filtros);
            navegacionForms.navegarReportesQuejasClientes(filtros);
            this.dispose();
        } catch (NegocioException ex) {
            JOptionPane.showMessageDialog(this,"Filtros con parametros incorrectos. "+ex.getMessage(), "Error",JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnBuscarActionPerformed

    private void btnRestablecerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRestablecerActionPerformed
        restablecerFiltros();
    }//GEN-LAST:event_btnRestablecerActionPerformed

    private void btnVolcerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVolcerActionPerformed
        navegacionForms.navegarReportesQuejasClientes();
        this.dispose();
    }//GEN-LAST:event_btnVolcerActionPerformed
    
    private FiltrosConsultaHistorialReportesNegocioDTO filtros() {
        String nombreCliente = txtFiltroNombre1.getText();
        CategoriaDTO nombreCategoria = new CategoriaDTO(null, comboCategorias.getSelectedItem().toString());
        EstadoReporteDTO nombreEstado = new EstadoReporteDTO(null, comboEstados1.getSelectedItem().toString());
        LocalDate fechaDesde = selectorFechaDesde.getDate();
        LocalDate fechaHasta = selectorFechaHasta.getDate();

        FiltrosConsultaHistorialReportesNegocioDTO filtros = new FiltrosConsultaHistorialReportesNegocioDTO(
                nombreCliente,
                nombreEstado,
                nombreCategoria,
                fechaDesde,
                fechaHasta
        );
        return filtros;
    }
    
    private void restablecerFiltros() {
        txtFiltroNombre1.setText("");
        selectorFechaDesde.setDate(null);
        selectorFechaHasta.setDate(null);
        comboCategorias.setSelectedIndex(0);
        comboEstados1.setSelectedIndex(0);
    }
    private void llenarComboCategorias() {
        try {
            List<CategoriaDTO> categorias = control.cargarCatalogoCategorias();
            for (CategoriaDTO c : categorias) {
                comboCategorias.addItem(c);
            }
        } catch (NegocioException ex) {
            JOptionPane.showMessageDialog(rootPane, ex);
        }
    }

    private void llenarComboEstados() {
        try {
            List<EstadoReporteDTO> estados = control.cargarCatalogoEstados();
            for (EstadoReporteDTO e : estados) {
                comboEstados1.addItem(e);
            }
        } catch (NegocioException ex) {
            JOptionPane.showMessageDialog(rootPane, ex);
        }
    }
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBuscar;
    private javax.swing.JButton btnRestablecer;
    private javax.swing.JButton btnVolcer;
    private javax.swing.JComboBox<CategoriaDTO> comboCategorias;
    private javax.swing.JComboBox<EstadoReporteDTO> comboEstados1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JLabel lblFechaDesde;
    private javax.swing.JLabel lblFechaHasta;
    private javax.swing.JLabel lblFiltroCategoria;
    private javax.swing.JLabel lblFiltroEstado;
    private javax.swing.JLabel lblFiltroNombre;
    private javax.swing.JLabel lblTitulo;
    private com.github.lgooddatepicker.components.DatePicker selectorFechaDesde;
    private com.github.lgooddatepicker.components.DatePicker selectorFechaHasta;
    private javax.swing.JTextField txtFiltroNombre1;
    // End of variables declaration//GEN-END:variables
}
