
package com.mycompany.fitlifegym_presentacion;

import com.mycompany.fitlifegym_dtos.ReporteAtencionDTO;
import com.mycompany.fitlifegym_dtos.ReporteIncidenteDTO;
import java.awt.Color;
import java.awt.Image;
import javax.swing.ImageIcon;
import javax.swing.SwingConstants;

/**
 *
 * @author Julian
 */
public class DetallesReporteSeleccionadoFORM extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(DetallesReporteSeleccionadoFORM.class.getName());
    ReporteIncidenteDTO reporteIncidenteSeleccionado;
    ReporteAtencionDTO reporteAtencionSeleccionado;
    private NavegacionForms control;
    
    /**
     * Creates new form DetallesReporteSeleccionadoFORM
     */
    public DetallesReporteSeleccionadoFORM(NavegacionForms control) {
        initComponents();
        this.setLocationRelativeTo(null);
        this.control = control;
    }
    public DetallesReporteSeleccionadoFORM(NavegacionForms control, ReporteIncidenteDTO reporteIncidenteSeleccionado) {
        initComponents();
        this.setLocationRelativeTo(null);
        this.control = control;
        this.reporteIncidenteSeleccionado = reporteIncidenteSeleccionado;
        mostrarDetallesReporteIncidente();
    }
    public DetallesReporteSeleccionadoFORM(NavegacionForms control, ReporteAtencionDTO reporteAtencionSeleccionado) {
        initComponents();
        this.setLocationRelativeTo(null);
        this.control = control;
        this.reporteAtencionSeleccionado = reporteAtencionSeleccionado;
        mostrarDetallesReporteAtencion();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        btnVolverAtras = new javax.swing.JButton();
        lblTitulo = new javax.swing.JLabel();
        lblSubtitulo = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        txtFolioReporte = new javax.swing.JTextField();
        lblDescripcionReporte = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtAreaDescripcion = new javax.swing.JTextArea();
        lblImagen = new javax.swing.JLabel();
        lblLugarImagen = new javax.swing.JLabel();
        btnResolverReporte = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(18, 18, 18));

        btnVolverAtras.setBackground(new java.awt.Color(255, 0, 51));
        btnVolverAtras.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnVolverAtras.setForeground(new java.awt.Color(255, 255, 255));
        btnVolverAtras.setText("<- Atras");
        btnVolverAtras.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        btnVolverAtras.addActionListener(this::btnVolverAtrasActionPerformed);

        lblTitulo.setFont(new java.awt.Font("Segoe UI", 3, 34)); // NOI18N
        lblTitulo.setForeground(new java.awt.Color(255, 255, 255));
        lblTitulo.setText("GymFit- Buzón Reportes Quejas/Sugerencias");

        lblSubtitulo.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblSubtitulo.setForeground(new java.awt.Color(255, 255, 255));
        lblSubtitulo.setText("Detalles Reporte Seleccionado");

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Folio: ");

        txtFolioReporte.setEditable(false);
        txtFolioReporte.setBackground(java.awt.Color.darkGray);
        txtFolioReporte.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        txtFolioReporte.setForeground(new java.awt.Color(255, 255, 255));
        txtFolioReporte.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 0));
        txtFolioReporte.setPreferredSize(new java.awt.Dimension(330, 39));

        lblDescripcionReporte.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        lblDescripcionReporte.setForeground(new java.awt.Color(255, 255, 255));
        lblDescripcionReporte.setText("Descripción: ");

        txtAreaDescripcion.setEditable(false);
        txtAreaDescripcion.setBackground(java.awt.Color.darkGray);
        txtAreaDescripcion.setColumns(20);
        txtAreaDescripcion.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        txtAreaDescripcion.setForeground(new java.awt.Color(255, 255, 255));
        txtAreaDescripcion.setLineWrap(true);
        txtAreaDescripcion.setRows(5);
        txtAreaDescripcion.setWrapStyleWord(true);
        txtAreaDescripcion.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 0));
        txtAreaDescripcion.setPreferredSize(new java.awt.Dimension(330, 161));
        jScrollPane1.setViewportView(txtAreaDescripcion);

        lblImagen.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        lblImagen.setForeground(new java.awt.Color(255, 255, 255));
        lblImagen.setText("Imagen: ");

        lblLugarImagen.setBackground(new java.awt.Color(153, 153, 153));
        lblLugarImagen.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblLugarImagen.setForeground(new java.awt.Color(255, 255, 255));
        lblLugarImagen.setPreferredSize(new java.awt.Dimension(130, 330));

        btnResolverReporte.setBackground(new java.awt.Color(255, 0, 51));
        btnResolverReporte.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnResolverReporte.setForeground(new java.awt.Color(255, 255, 255));
        btnResolverReporte.setText("Resolver Reporte");
        btnResolverReporte.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        btnResolverReporte.addActionListener(this::btnResolverReporteActionPerformed);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(btnVolverAtras, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addComponent(lblTitulo)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(188, 188, 188)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblDescripcionReporte)
                    .addComponent(jLabel1)
                    .addComponent(lblImagen))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtFolioReporte, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane1)
                    .addComponent(lblLugarImagen, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(227, 227, 227))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(lblSubtitulo)
                        .addGap(271, 271, 271))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(btnResolverReporte, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(314, 314, 314))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lblTitulo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnVolverAtras, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(12, 12, 12)
                .addComponent(lblSubtitulo)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(18, 18, 18))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(txtFolioReporte, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblDescripcionReporte)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(lblImagen))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lblLugarImagen, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addComponent(btnResolverReporte, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(23, 23, 23))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnVolverAtrasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVolverAtrasActionPerformed
        control.navegarReportesQuejasClientes();
        this.dispose();
    }//GEN-LAST:event_btnVolverAtrasActionPerformed

    private void btnResolverReporteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnResolverReporteActionPerformed
        control.navegarResolverReporteSeleccionado(reporteIncidenteSeleccionado);
        this.dispose();
    }//GEN-LAST:event_btnResolverReporteActionPerformed
    
    private void mostrarDetallesReporteIncidente(){
        txtFolioReporte.setText(reporteIncidenteSeleccionado.folio());
        txtAreaDescripcion.setText(reporteIncidenteSeleccionado.descripcion());
        jScrollPane1.setBorder(null);

        if (reporteIncidenteSeleccionado.imagen() != null) {
            lblLugarImagen.setText("");
            ImageIcon icono = new ImageIcon(reporteIncidenteSeleccionado.imagen().imagen());
            Image imagenEscalada = icono.getImage().getScaledInstance(
                    lblLugarImagen.getWidth(),
                    lblLugarImagen.getHeight(),
                    Image.SCALE_SMOOTH
            );

            lblLugarImagen.setIcon(new ImageIcon(imagenEscalada));
        } else {
            lblLugarImagen.setIcon(null);
            lblLugarImagen.setHorizontalAlignment(SwingConstants.CENTER);
            lblLugarImagen.setVerticalAlignment(SwingConstants.CENTER);
            lblLugarImagen.setText("REPORTE SIN IMAGEN");
        }
    }
    private void mostrarDetallesReporteAtencion(){
        txtFolioReporte.setText(reporteAtencionSeleccionado.folio());
        txtAreaDescripcion.setText(reporteAtencionSeleccionado.solucion());
        jScrollPane1.setBorder(null);
        lblDescripcionReporte.setText("Solución: ");
        if (reporteAtencionSeleccionado.imagen() != null) {
            lblLugarImagen.setText("");
            ImageIcon icono = new ImageIcon(reporteAtencionSeleccionado.imagen().imagen());
            Image imagenEscalada = icono.getImage().getScaledInstance(
                    lblLugarImagen.getWidth(),
                    lblLugarImagen.getHeight(),
                    Image.SCALE_SMOOTH
            );

            lblLugarImagen.setIcon(new ImageIcon(imagenEscalada));
        } else {
            lblLugarImagen.setIcon(null);
            lblLugarImagen.setHorizontalAlignment(SwingConstants.CENTER);
            lblLugarImagen.setVerticalAlignment(SwingConstants.CENTER);
            lblLugarImagen.setText("REPORTE SIN IMAGEN");
        } 
        btnResolverReporte.setEnabled(false);
        btnResolverReporte.setText("Reporte resuelto");
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnResolverReporte;
    private javax.swing.JButton btnVolverAtras;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblDescripcionReporte;
    private javax.swing.JLabel lblImagen;
    private javax.swing.JLabel lblLugarImagen;
    private javax.swing.JLabel lblSubtitulo;
    private javax.swing.JLabel lblTitulo;
    private javax.swing.JTextArea txtAreaDescripcion;
    private javax.swing.JTextField txtFolioReporte;
    // End of variables declaration//GEN-END:variables
}
