
package com.mycompany.fitlifegym_presentacion;

import com.mycompany.fitlifegym_dtos.CategoriaDTO;
import com.mycompany.fitlifegym_dtos.ImagenDTO;
import com.mycompany.fitlifegym_dtos.NuevoReporteIncidenteDTO;
import com.mycompany.fitlifegym_dtos.ReporteIncidenteGeneradoDTO;
import com.mycompany.fitlifegym_negocio.NegocioException;
import com.mycompany.fitlifegym_presentacion.sesion.SesionUsuario;
import java.io.File;
import java.io.IOException;
import java.nio.file.Files;
import java.time.LocalDate;
import java.util.List;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.filechooser.FileNameExtensionFilter;
import com.mycompany.fitlifegym_presentacion.sesion.SesionUsuario;
import java.awt.Image;


/**
 *
 * @author Julian
 */
public class GenerarNuevoReporteFORM extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(GenerarNuevoReporteFORM.class.getName());
    private ControlForms control;
    private byte[] imagenSeleccionada;
    /**
     * Creates new form GenerarNuevoReporteFORM
     */
    public GenerarNuevoReporteFORM(ControlForms control) {
        initComponents();
        this.setLocationRelativeTo(null);
        this.control = control;
        llenarComboCategorias();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        btnVolverAtras = new javax.swing.JButton();
        lblTitulo = new javax.swing.JLabel();
        lblCategoria = new javax.swing.JLabel();
        comboCategorias = new javax.swing.JComboBox<>();
        lblAsunto = new javax.swing.JLabel();
        txtAsunto = new javax.swing.JTextField();
        lblDescripcion = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtAreaDescripcion = new javax.swing.JTextArea();
        lblImagen = new javax.swing.JLabel();
        btnSeleccionarImagen = new javax.swing.JButton();
        lblLugarImagen = new javax.swing.JLabel();
        btnGenerarReporte = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(18, 18, 18));

        btnVolverAtras.setBackground(new java.awt.Color(255, 0, 51));
        btnVolverAtras.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnVolverAtras.setForeground(new java.awt.Color(255, 255, 255));
        btnVolverAtras.setText("<- Atras");
        btnVolverAtras.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        btnVolverAtras.addActionListener(this::btnVolverAtrasActionPerformed);

        lblTitulo.setFont(new java.awt.Font("Segoe UI", 3, 34)); // NOI18N
        lblTitulo.setForeground(new java.awt.Color(255, 255, 255));
        lblTitulo.setText("GymFit- Generar Nuevo Reporte");

        lblCategoria.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblCategoria.setForeground(new java.awt.Color(255, 255, 255));
        lblCategoria.setText("Categoría: ");

        comboCategorias.setBackground(new java.awt.Color(255, 255, 255));
        comboCategorias.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        comboCategorias.setForeground(new java.awt.Color(0, 0, 0));

        lblAsunto.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblAsunto.setForeground(new java.awt.Color(255, 255, 255));
        lblAsunto.setText("Asunto: ");

        txtAsunto.setBackground(new java.awt.Color(255, 255, 255));
        txtAsunto.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        txtAsunto.setForeground(new java.awt.Color(0, 0, 0));
        txtAsunto.setMaximumSize(new java.awt.Dimension(298, 35));

        lblDescripcion.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblDescripcion.setForeground(new java.awt.Color(255, 255, 255));
        lblDescripcion.setText("Descripción:");

        txtAreaDescripcion.setBackground(new java.awt.Color(255, 255, 255));
        txtAreaDescripcion.setColumns(20);
        txtAreaDescripcion.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        txtAreaDescripcion.setForeground(new java.awt.Color(0, 0, 0));
        txtAreaDescripcion.setRows(5);
        jScrollPane1.setViewportView(txtAreaDescripcion);

        lblImagen.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblImagen.setForeground(new java.awt.Color(255, 255, 255));
        lblImagen.setText("Imagen:");

        btnSeleccionarImagen.setBackground(new java.awt.Color(102, 102, 102));
        btnSeleccionarImagen.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        btnSeleccionarImagen.setForeground(new java.awt.Color(255, 255, 255));
        btnSeleccionarImagen.setText("Seleccionar Imagen");
        btnSeleccionarImagen.addActionListener(this::btnSeleccionarImagenActionPerformed);

        btnGenerarReporte.setBackground(new java.awt.Color(255, 0, 51));
        btnGenerarReporte.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        btnGenerarReporte.setForeground(new java.awt.Color(255, 255, 255));
        btnGenerarReporte.setText("Generar Reporte");
        btnGenerarReporte.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        btnGenerarReporte.addActionListener(this::btnGenerarReporteActionPerformed);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(btnVolverAtras, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(119, 119, 119)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblTitulo)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblCategoria)
                            .addComponent(lblAsunto)
                            .addComponent(lblDescripcion)
                            .addComponent(lblImagen))
                        .addGap(28, 28, 28)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1)
                            .addComponent(txtAsunto, javax.swing.GroupLayout.PREFERRED_SIZE, 298, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(comboCategorias, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblLugarImagen, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(82, 82, 82)))
                .addGap(169, 169, 169))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(btnGenerarReporte, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(300, 300, 300))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(btnSeleccionarImagen)
                        .addGap(310, 310, 310))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnVolverAtras, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblTitulo))
                .addGap(43, 43, 43)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCategoria)
                    .addComponent(comboCategorias, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblAsunto)
                    .addComponent(txtAsunto, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(lblDescripcion))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(71, 71, 71)
                        .addComponent(lblImagen))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(btnSeleccionarImagen, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblLugarImagen, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(24, 24, 24)
                .addComponent(btnGenerarReporte, javax.swing.GroupLayout.DEFAULT_SIZE, 44, Short.MAX_VALUE)
                .addGap(12, 12, 12))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnGenerarReporteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGenerarReporteActionPerformed
        boolean generado = generarReporteIncidente();
        if(generado){
           control.navegarReporteGenerado();
            this.dispose(); 
        }
    }//GEN-LAST:event_btnGenerarReporteActionPerformed

    private void btnSeleccionarImagenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSeleccionarImagenActionPerformed
        seleccionarImagen();
    }//GEN-LAST:event_btnSeleccionarImagenActionPerformed

    private void btnVolverAtrasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVolverAtrasActionPerformed
        control.navegarInicioBuzonQuejas();
        this.dispose();
    }//GEN-LAST:event_btnVolverAtrasActionPerformed
    
    private boolean generarReporteIncidente(){
        try {
            CategoriaDTO nombreCategoria = new CategoriaDTO(null,comboCategorias.getSelectedItem().toString());
            String asunto = txtAsunto.getText();
            String descripcion = txtAreaDescripcion.getText();
            ImagenDTO imagen = null;
            if (this.imagenSeleccionada != null) {
                imagen = new ImagenDTO(this.imagenSeleccionada,null);
            }
            LocalDate fechaGenerado = LocalDate.now();
            NuevoReporteIncidenteDTO reporteIncidente = new NuevoReporteIncidenteDTO(
                    asunto, nombreCategoria, descripcion, fechaGenerado, imagen,
                    SesionUsuario.getInstancia().getClienteActual()
            );
            ReporteIncidenteGeneradoDTO reporteGenerado = control.generarReporteIncidente(reporteIncidente);
            return reporteGenerado != null;
        } catch (NegocioException ex) {
            JOptionPane.showMessageDialog( this, "Error al generar el reporte de incidente. "+ex.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
            return false;
        }
    }
    private void seleccionarImagen(){
        try {
            JFileChooser selector = new JFileChooser();
            FileNameExtensionFilter filtro = new FileNameExtensionFilter("Imágenes JPG y PNG", "jpg", "jpeg", "png");
            selector.setFileFilter(filtro);
            int resultado = selector.showOpenDialog(this);

            if (resultado == JFileChooser.APPROVE_OPTION) {
            
                File archivo = selector.getSelectedFile();
                this.imagenSeleccionada = Files.readAllBytes(archivo.toPath());
                
                ImageIcon icono = new ImageIcon(this.imagenSeleccionada);
                Image imagenEscalada = icono.getImage().getScaledInstance(
                            lblLugarImagen.getWidth(),
                            lblLugarImagen.getHeight(),
                            Image.SCALE_SMOOTH
                );

                lblLugarImagen.setIcon(new ImageIcon(imagenEscalada));
            }
        }catch (IOException ex) {
            JOptionPane.showMessageDialog(this, "Error al leer la imagen.");
        }
    }
    private void llenarComboCategorias(){
        try {
            List<CategoriaDTO> categorias = control.cargarCatalogoCategorias();
            for(CategoriaDTO c: categorias){
                comboCategorias.addItem(c);
            }
        } catch (NegocioException ex) {
            JOptionPane.showMessageDialog(rootPane, ex);
        }
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnGenerarReporte;
    private javax.swing.JButton btnSeleccionarImagen;
    private javax.swing.JButton btnVolverAtras;
    private javax.swing.JComboBox<CategoriaDTO> comboCategorias;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblAsunto;
    private javax.swing.JLabel lblCategoria;
    private javax.swing.JLabel lblDescripcion;
    private javax.swing.JLabel lblImagen;
    private javax.swing.JLabel lblLugarImagen;
    private javax.swing.JLabel lblTitulo;
    private javax.swing.JTextArea txtAreaDescripcion;
    private javax.swing.JTextField txtAsunto;
    // End of variables declaration//GEN-END:variables
}
