
package com.mycompany.fitlifegym_presentacion;

import com.mycompany.fitlifegym_dtos.FiltrosConsultaHistorialReportesNegocioDTO;
import com.mycompany.fitlifegym_dtos.ReporteIncidenteDTO;
import com.mycompany.fitlifegym_negocio.NegocioException;
import com.mycompany.fitlifegym_presentacion.sesion.SesionUsuario;
import java.awt.Color;
import java.awt.Component;
import java.util.List;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.JTextArea;
import javax.swing.table.DefaultTableCellRenderer;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Julian
 */
public class MisReportesGeneradosFORM extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(MisReportesGeneradosFORM.class.getName());
    private NavegacionForms navegacionForms;
    private ControlSubsistemaQuejasSugerencias control;
    private FiltrosConsultaHistorialReportesNegocioDTO filtros;
    private List<ReporteIncidenteDTO> reportesIncidentes;
    /**
     * Creates new form ReportesQuejasClientesFORM
     */
    public MisReportesGeneradosFORM(NavegacionForms navegacionForms, ControlSubsistemaQuejasSugerencias control) {
        initComponents();
        ocultarFolioTabla();
        diseñoTabla();
        this.navegacionForms = navegacionForms;
        this.control = control;
        this.setLocationRelativeTo(null);
        cargarTabla();
        colorBotones();
    }
    public MisReportesGeneradosFORM(NavegacionForms navegacionForms, FiltrosConsultaHistorialReportesNegocioDTO filtros,ControlSubsistemaQuejasSugerencias control ) {
        initComponents();
        diseñoTabla();
        this.navegacionForms = navegacionForms;
        this.filtros = filtros;
        this.control = control;
        this.setLocationRelativeTo(null);
        ocultarFolioTabla();
        llenarTablaReportesFiltros();
        colorBotones();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        btnSalir = new javax.swing.JButton();
        lblTitulo = new javax.swing.JLabel();
        btnBuscadorReportes = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblRegistrosReportes = new javax.swing.JTable();
        btnSeleccionarReporte = new javax.swing.JButton();
        btnMostrarTodos = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(18, 18, 18));

        btnSalir.setBackground(new java.awt.Color(255, 0, 51));
        btnSalir.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnSalir.setForeground(new java.awt.Color(255, 255, 255));
        btnSalir.setText("<- Atras");
        btnSalir.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        btnSalir.addActionListener(this::btnSalirActionPerformed);

        lblTitulo.setFont(new java.awt.Font("Segoe UI", 3, 34)); // NOI18N
        lblTitulo.setForeground(new java.awt.Color(255, 255, 255));
        lblTitulo.setText("GymFit- Mis Reportes Generados");

        btnBuscadorReportes.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        btnBuscadorReportes.setForeground(new java.awt.Color(255, 255, 255));
        btnBuscadorReportes.setText("Buscador Reportes");
        btnBuscadorReportes.addActionListener(this::btnBuscadorReportesActionPerformed);

        tblRegistrosReportes.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Folio", "Asunto", "Categoría", "Estado Reporte", "Cliente", "Fecha"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tblRegistrosReportes);

        btnSeleccionarReporte.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnSeleccionarReporte.setForeground(new java.awt.Color(255, 255, 255));
        btnSeleccionarReporte.setText("Seleccionar Reporte");
        btnSeleccionarReporte.addActionListener(this::btnSeleccionarReporteActionPerformed);

        btnMostrarTodos.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnMostrarTodos.setForeground(new java.awt.Color(255, 255, 255));
        btnMostrarTodos.setText("Mostrar Todos");
        btnMostrarTodos.addActionListener(this::btnMostrarTodosActionPerformed);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(btnSalir, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(112, 112, 112)
                        .addComponent(lblTitulo))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(297, 297, 297)
                        .addComponent(btnBuscadorReportes, javax.swing.GroupLayout.PREFERRED_SIZE, 301, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addComponent(btnSeleccionarReporte)
                                .addGap(18, 18, 18)
                                .addComponent(btnMostrarTodos))
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 857, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(21, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(btnSalir, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(25, 25, 25))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(lblTitulo)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)))
                .addComponent(btnBuscadorReportes)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 407, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnSeleccionarReporte)
                    .addComponent(btnMostrarTodos, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 22, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalirActionPerformed
        navegacionForms.navegarInicioBuzonQuejas();
        this.dispose();
    }//GEN-LAST:event_btnSalirActionPerformed

    private void btnBuscadorReportesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscadorReportesActionPerformed
        navegacionForms.navegarBuscadorMisReportesCliente();
        this.dispose();
    }//GEN-LAST:event_btnBuscadorReportesActionPerformed

    private void btnMostrarTodosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMostrarTodosActionPerformed
        cargarTabla();
    }//GEN-LAST:event_btnMostrarTodosActionPerformed

    private void btnSeleccionarReporteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSeleccionarReporteActionPerformed
        ReporteIncidenteDTO reporteSeleccionado = seleccionarReporte();
        if(reporteSeleccionado == null){
            JOptionPane.showMessageDialog(this,"Seleccione un reporte.");
            return;
        }
        navegacionForms.navegarDetallesReporteSeleccionadoCliente(reporteSeleccionado);
        this.dispose();
    }//GEN-LAST:event_btnSeleccionarReporteActionPerformed
    
    private ReporteIncidenteDTO seleccionarReporte(){
        try {
            int filaSeleccionada = tblRegistrosReportes.getSelectedRow();
            
            if (filaSeleccionada == -1) {
                return null;
            }
            
            String folio = tblRegistrosReportes.getValueAt(filaSeleccionada, 0).toString();
            
            ReporteIncidenteDTO reporte = control.consultarReporteIncidentePorFolio(folio);
            return reporte;
        } catch (NegocioException ex) {
            JOptionPane.showMessageDialog(this,"Error al cargar los reportes.", "Error",JOptionPane.ERROR_MESSAGE);
            return null;
        }
    }
    
    private void cargarTabla() {
        try {
            List<ReporteIncidenteDTO> reportes = control.consultarReportesIncidentesPorCliente(
                new FiltrosConsultaHistorialReportesNegocioDTO(SesionUsuario.getInstancia().getClienteActual().getIdCliente(),null,null,null,null)
            );
            llenarTablaReportes(reportes);
        } catch (NegocioException ex) {
            JOptionPane.showMessageDialog( this, "Error al cargar los reportes de incidentes. "+ex.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
        }
    }
    
    private void llenarTablaReportesFiltros(){
        try {
            List<ReporteIncidenteDTO> reportes = control.consultarReportesIncidentesPorCliente(filtros);
            DefaultTableModel modelo = (DefaultTableModel) tblRegistrosReportes.getModel();
            
            modelo.setRowCount(0);
            
            for (ReporteIncidenteDTO reporte : reportes) {
                
                Object[] fila = {
                    reporte.folio(),
                    reporte.asunto(),
                    reporte.categoria().categoria(),
                    reporte.estado().estado(),
                    reporte.cliente().getNombreCompleto(),
                    reporte.fecha().toString()
                };
                
                modelo.addRow(fila);
            }
        } catch (NegocioException ex) {
            JOptionPane.showMessageDialog( this, "Error al cargar los reportes de incidentes. "+ex.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
        }
    }
    
    private void llenarTablaReportes(List<ReporteIncidenteDTO> reportes) {
            this.reportesIncidentes = reportes;
            DefaultTableModel modelo = (DefaultTableModel) tblRegistrosReportes.getModel();
            
            modelo.setRowCount(0);
            
            for (ReporteIncidenteDTO reporte : reportesIncidentes) {
                
                Object[] fila = {
                    reporte.folio(),
                    reporte.asunto(),
                    reporte.categoria().categoria(),
                    reporte.estado().estado(),
                    reporte.cliente().getNombreCompleto(),
                    reporte.fecha().toString()
                };
                
                modelo.addRow(fila);
            }
    }
    
    private void ocultarFolioTabla(){
        tblRegistrosReportes.getColumnModel()
                .getColumn(0)
                .setMinWidth(0);

        tblRegistrosReportes.getColumnModel()
                .getColumn(0)
                .setMaxWidth(0);

        tblRegistrosReportes.getColumnModel()
                .getColumn(0)
                .setWidth(0);
    }
    
    private void diseñoTabla() {
        tblRegistrosReportes.setRowHeight(30);
        tblRegistrosReportes.setBackground(new java.awt.Color(30, 30, 30));
        tblRegistrosReportes.setForeground(java.awt.Color.WHITE);
        tblRegistrosReportes.setGridColor(new java.awt.Color(225, 6, 0));
        tblRegistrosReportes.getTableHeader().setBackground(new java.awt.Color(30, 30, 30));
        tblRegistrosReportes.getTableHeader().setForeground(java.awt.Color.WHITE);
        tblRegistrosReportes.getTableHeader().setFont(new java.awt.Font("Arial", java.awt.Font.BOLD, 16));
        jScrollPane1.getViewport().setBackground(new java.awt.Color(30, 30, 30));
        DefaultTableCellRenderer renderCentrado = new DefaultTableCellRenderer();
        renderCentrado.setHorizontalAlignment(JLabel.CENTER);
        tblRegistrosReportes.getColumnModel().getColumn(0).setCellRenderer(renderCentrado);
        tblRegistrosReportes.getColumnModel().getColumn(2).setCellRenderer(renderCentrado);
        tblRegistrosReportes.getColumnModel().getColumn(3).setCellRenderer(renderCentrado);
        tblRegistrosReportes.getColumnModel().getColumn(4).setCellRenderer(renderCentrado);
        tblRegistrosReportes.getColumnModel().getColumn(5).setCellRenderer(renderCentrado);
        tblRegistrosReportes.getColumnModel().getColumn(1)
                .setCellRenderer(new DefaultTableCellRenderer() {

                    private final JTextArea area = new JTextArea();

                    @Override
                    public Component getTableCellRendererComponent(JTable table, Object value, boolean isSelected,
                            boolean hasFocus, int row, int column) {
                        area.setText(value == null ? "" : value.toString());
                        area.setLineWrap(true);
                        area.setWrapStyleWord(true);
                        area.setForeground(Color.WHITE);
                        area.setBackground(new Color(30, 30, 30));
                        area.setFont(table.getFont());
                        int altura = area.getPreferredSize().height;
                        if (table.getRowHeight(row) != altura) {
                            table.setRowHeight(row, altura);
                        }
                        return area;
                    }
                });
    }
    
    private void colorBotones(){
        btnBuscadorReportes.setBackground(new Color(86,86,86));
        btnBuscadorReportes.setForeground(Color.WHITE);
        btnSeleccionarReporte.setBackground(new Color(86,86,86));
        btnSeleccionarReporte.setForeground(Color.WHITE);
        btnMostrarTodos.setBackground(new Color(86,86,86));
        btnMostrarTodos.setForeground(Color.WHITE);
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBuscadorReportes;
    private javax.swing.JButton btnMostrarTodos;
    private javax.swing.JButton btnSalir;
    private javax.swing.JButton btnSeleccionarReporte;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblTitulo;
    private javax.swing.JTable tblRegistrosReportes;
    // End of variables declaration//GEN-END:variables
}
