
package com.mycompany.fitlifegym_presentacion;

import com.mycompany.fitlifegym_dtos.FiltrosConsultaHistorialReportesNegocioDTO;
import com.mycompany.fitlifegym_dtos.RegistroReporteAdminDTO;
import com.mycompany.fitlifegym_dtos.ReporteAtencionDTO;
import com.mycompany.fitlifegym_dtos.ReporteIncidenteDTO;
import com.mycompany.fitlifegym_dtos.TipoReporteDTO;
import com.mycompany.fitlifegym_negocio.NegocioException;
import java.awt.Color;
import java.awt.Component;
import java.io.File;
import java.io.IOException;
import java.nio.file.Files;
import java.nio.file.Paths;
import java.util.List;
import javax.swing.JFileChooser;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.JTextArea;
import javax.swing.table.DefaultTableCellRenderer;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Julian
 */
public class ReportesQuejasClientesFORM extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(ReportesQuejasClientesFORM.class.getName());
    private NavegacionForms navegacionForms;
    private ControlSubsistemaQuejasSugerencias control;
    private List<RegistroReporteAdminDTO> registrosReportes;
    private FiltrosConsultaHistorialReportesNegocioDTO filtros;
    private ReporteAtencionDTO reporteAtencionSeleccionado;
    private ReporteIncidenteDTO reporteIncidenteSeleccionado;
    /**
     * Creates new form ReportesQuejasClientesFORM
     */
    public ReportesQuejasClientesFORM(NavegacionForms navegacionForms, ControlSubsistemaQuejasSugerencias control) {
        initComponents();
        diseñoTabla();
        this.setLocationRelativeTo(null);
        ocultarFolioTabla();
        this.control = control;
        this.navegacionForms = navegacionForms;
        cargarTabla();
        colorBotones();
    }
    public ReportesQuejasClientesFORM(NavegacionForms navegacionForms, FiltrosConsultaHistorialReportesNegocioDTO filtros, ControlSubsistemaQuejasSugerencias control) {
        initComponents();
        diseñoTabla();
        this.setLocationRelativeTo(null);
        ocultarFolioTabla();
        this.navegacionForms = navegacionForms;
        this.filtros = filtros;
        this.control = control;
        cargarTablaFiltros();
        colorBotones();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        btnSalir = new javax.swing.JButton();
        lblTitulo = new javax.swing.JLabel();
        btnBuscadorReportes = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblRegistrosReportes = new javax.swing.JTable();
        btnSeleccionarReporte = new javax.swing.JButton();
        btnExportarPdf = new javax.swing.JButton();
        btnMostrarTodos = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(18, 18, 18));

        btnSalir.setBackground(new java.awt.Color(255, 0, 51));
        btnSalir.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnSalir.setForeground(new java.awt.Color(255, 255, 255));
        btnSalir.setText("Salir");
        btnSalir.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        btnSalir.addActionListener(this::btnSalirActionPerformed);

        lblTitulo.setFont(new java.awt.Font("Segoe UI", 3, 34)); // NOI18N
        lblTitulo.setForeground(new java.awt.Color(255, 255, 255));
        lblTitulo.setText("GymFit- Buzón Reportes Quejas/Sugerencias");

        btnBuscadorReportes.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        btnBuscadorReportes.setForeground(new java.awt.Color(255, 255, 255));
        btnBuscadorReportes.setText("Buscador Reportes");
        btnBuscadorReportes.addActionListener(this::btnBuscadorReportesActionPerformed);

        tblRegistrosReportes.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "Folio", "Asunto", "Categoría", "Estado Reporte", "Cliente", "Fecha", "Tipo"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tblRegistrosReportes);

        btnSeleccionarReporte.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnSeleccionarReporte.setForeground(new java.awt.Color(255, 255, 255));
        btnSeleccionarReporte.setText("Seleccionar Reporte");
        btnSeleccionarReporte.addActionListener(this::btnSeleccionarReporteActionPerformed);

        btnExportarPdf.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnExportarPdf.setForeground(new java.awt.Color(255, 255, 255));
        btnExportarPdf.setText("Exportar PDF");
        btnExportarPdf.addActionListener(this::btnExportarPdfActionPerformed);

        btnMostrarTodos.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnMostrarTodos.setForeground(new java.awt.Color(255, 255, 255));
        btnMostrarTodos.setText("Mostrar Todos");
        btnMostrarTodos.addActionListener(this::btnMostrarTodosActionPerformed);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(btnSalir, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(31, 31, 31)
                        .addComponent(lblTitulo))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(297, 297, 297)
                        .addComponent(btnBuscadorReportes, javax.swing.GroupLayout.PREFERRED_SIZE, 301, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addComponent(btnSeleccionarReporte)
                                .addGap(18, 18, 18)
                                .addComponent(btnExportarPdf)
                                .addGap(18, 18, 18)
                                .addComponent(btnMostrarTodos))
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 857, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(21, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(13, 13, 13)
                        .addComponent(lblTitulo))
                    .addComponent(btnSalir, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnBuscadorReportes)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 407, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnSeleccionarReporte)
                    .addComponent(btnExportarPdf)
                    .addComponent(btnMostrarTodos, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 22, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalirActionPerformed
        navegacionForms.navegarMenuPrincipalAdmin();
        this.dispose();
    }//GEN-LAST:event_btnSalirActionPerformed

    private void btnSeleccionarReporteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSeleccionarReporteActionPerformed
        seleccionarReporte();
        this.dispose();
    }//GEN-LAST:event_btnSeleccionarReporteActionPerformed

    private void btnExportarPdfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExportarPdfActionPerformed
        generarReportePdf();
    }//GEN-LAST:event_btnExportarPdfActionPerformed

    private void btnMostrarTodosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMostrarTodosActionPerformed
        cargarTabla();
    }//GEN-LAST:event_btnMostrarTodosActionPerformed

    private void btnBuscadorReportesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscadorReportesActionPerformed
        navegacionForms.navegarBuscadorAdmin();
        this.dispose();
    }//GEN-LAST:event_btnBuscadorReportesActionPerformed
    
    private void generarReportePdf(){
        JFileChooser fileChooser = new JFileChooser();
        fileChooser.setDialogTitle("Guardar PDF");
        fileChooser.setSelectedFile(new File("ReporteDeRegistros.pdf"));
        int resultado = fileChooser.showSaveDialog(this);
        if (resultado == JFileChooser.APPROVE_OPTION) {
            try {
                String ruta = fileChooser.getSelectedFile().getAbsolutePath();
                if (!ruta.endsWith(".pdf")) {
                    ruta += ".pdf";
                }
                byte[] pdf = control.generarReportePdf(registrosReportes);
                Files.write(Paths.get(ruta),pdf);

                JOptionPane.showMessageDialog(this, "PDF generado exitosamente en:\n" + ruta, "Éxito", JOptionPane.INFORMATION_MESSAGE);
            } catch (NegocioException | IOException ex) {
                JOptionPane.showMessageDialog(this, "No se pudo generar el pdf correctamente. "+ex.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
            }
        }
    }
    
    private void seleccionarReporte() {
        try {
            int filaVista = tblRegistrosReportes.getSelectedRow();
            int filaModelo = tblRegistrosReportes.convertRowIndexToModel(filaVista);

            RegistroReporteAdminDTO reporte = registrosReportes.get(filaModelo);
            if(reporte.tipo() == TipoReporteDTO.INCIDENTE){
                String folio = tblRegistrosReportes.getValueAt(filaModelo, 0).toString();
                this.reporteIncidenteSeleccionado = control.consultarReporteIncidentePorFolio(folio);
                navegacionForms.navegarDetallesReporteSeleccionadoForm(reporteIncidenteSeleccionado);
            }else if(reporte.tipo() == TipoReporteDTO.ATENCION){
                String folio = tblRegistrosReportes.getValueAt(filaModelo,0).toString();
                this.reporteAtencionSeleccionado = control.consultarReporteAtencionPorFolio(folio);
                navegacionForms.navegarDetallesReporteSeleccionadoForm(reporteAtencionSeleccionado);
            }
            
        } catch (NegocioException ex) {
            JOptionPane.showMessageDialog(this, "Error al cargar el reporte. "+ex.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
        }
    }
    
    private void cargarTablaFiltros(){
        try {
            List<RegistroReporteAdminDTO> reportes = control.consultarTodosLosReportesFiltrados(filtros);
            llenarTablaReportes(reportes);
        } catch (NegocioException ex) {
            JOptionPane.showMessageDialog(this, "Error al cargar los reportes. "+ ex.getMessage(), "Error",JOptionPane.ERROR_MESSAGE);
            
        }
    }
    
    private void cargarTabla() {
        try {
            List<RegistroReporteAdminDTO> reportes = control.consultarTodosLosReportes();
            llenarTablaReportes(reportes);
        } catch (NegocioException ex) {
            JOptionPane.showMessageDialog(this, "Error al cargar los reportes. "+ ex.getMessage(), "Error",JOptionPane.ERROR_MESSAGE);
        }
    }
    private void llenarTablaReportes(List<RegistroReporteAdminDTO> reportes) {
            this.registrosReportes = reportes;
            DefaultTableModel modelo = (DefaultTableModel) tblRegistrosReportes.getModel();
            
            modelo.setRowCount(0);
            
            for (RegistroReporteAdminDTO reporte : registrosReportes) {
                
                Object[] fila = {
                    reporte.folio(),
                    reporte.asunto(),
                    reporte.categoria().categoria(),
                    reporte.estado().estado(),
                    reporte.cliente().getNombreCompleto(),
                    reporte.fecha().toString(),
                    reporte.tipo()
                };
                
                modelo.addRow(fila);
            }
    }
    private void ocultarFolioTabla(){
        tblRegistrosReportes.getColumnModel()
                .getColumn(0)
                .setMinWidth(0);

        tblRegistrosReportes.getColumnModel()
                .getColumn(0)
                .setMaxWidth(0);

        tblRegistrosReportes.getColumnModel()
                .getColumn(0)
                .setWidth(0);
    }
    
    private void diseñoTabla() {
        tblRegistrosReportes.setRowHeight(30);
        tblRegistrosReportes.setBackground(new java.awt.Color(30, 30, 30));
        tblRegistrosReportes.setForeground(java.awt.Color.WHITE);
        tblRegistrosReportes.setGridColor(new java.awt.Color(225, 6, 0));
        tblRegistrosReportes.getTableHeader().setBackground(new java.awt.Color(30, 30, 30));
        tblRegistrosReportes.getTableHeader().setForeground(java.awt.Color.WHITE);
        tblRegistrosReportes.getTableHeader().setFont(new java.awt.Font("Arial", java.awt.Font.BOLD, 16));
        jScrollPane1.getViewport().setBackground(new java.awt.Color(30, 30, 30));
        DefaultTableCellRenderer renderCentrado = new DefaultTableCellRenderer();
        renderCentrado.setHorizontalAlignment(JLabel.CENTER);
        tblRegistrosReportes.getColumnModel().getColumn(0).setCellRenderer(renderCentrado);
        tblRegistrosReportes.getColumnModel().getColumn(2).setCellRenderer(renderCentrado);
        tblRegistrosReportes.getColumnModel().getColumn(3).setCellRenderer(renderCentrado);
        tblRegistrosReportes.getColumnModel().getColumn(4).setCellRenderer(renderCentrado);
        tblRegistrosReportes.getColumnModel().getColumn(5).setCellRenderer(renderCentrado);
        tblRegistrosReportes.getColumnModel().getColumn(6).setCellRenderer(renderCentrado);
        tblRegistrosReportes.getColumnModel().getColumn(1)
                .setCellRenderer(new DefaultTableCellRenderer() {

                    private final JTextArea area = new JTextArea();

                    @Override
                    public Component getTableCellRendererComponent(JTable table, Object value, boolean isSelected,
                            boolean hasFocus, int row, int column) {
                        area.setText(value == null ? "" : value.toString());
                        area.setLineWrap(true);
                        area.setWrapStyleWord(true);
                        area.setForeground(Color.WHITE);
                        area.setBackground(new Color(30, 30, 30));
                        area.setFont(table.getFont());
                        int altura = area.getPreferredSize().height;
                        if (table.getRowHeight(row) != altura) {
                            table.setRowHeight(row, altura);
                        }
                        return area;
                    }
                });
    }
    
    private void colorBotones(){
        btnBuscadorReportes.setBackground(new Color(86,86,86));
        btnBuscadorReportes.setForeground(Color.WHITE);
        btnSeleccionarReporte.setBackground(new Color(86,86,86));
        btnSeleccionarReporte.setForeground(Color.WHITE);
        btnMostrarTodos.setBackground(new Color(86,86,86));
        btnMostrarTodos.setForeground(Color.WHITE);
        btnExportarPdf.setBackground(new Color(86,86,86));
        btnExportarPdf.setForeground(Color.WHITE);
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBuscadorReportes;
    private javax.swing.JButton btnExportarPdf;
    private javax.swing.JButton btnMostrarTodos;
    private javax.swing.JButton btnSalir;
    private javax.swing.JButton btnSeleccionarReporte;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblTitulo;
    private javax.swing.JTable tblRegistrosReportes;
    // End of variables declaration//GEN-END:variables
}
