/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.fitlifegym_presentacion;

import com.mycompany.fitlifegym_dtos.AtenderReporteDTO;
import com.mycompany.fitlifegym_dtos.ImagenDTO;
import com.mycompany.fitlifegym_dtos.ReporteAtencionGeneradoDTO;
import com.mycompany.fitlifegym_dtos.ReporteIncidenteDTO;
import com.mycompany.fitlifegym_negocio.NegocioException;
import java.awt.Image;
import java.io.File;
import java.io.IOException;
import java.nio.file.Files;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.filechooser.FileNameExtensionFilter;

/**
 *
 * @author Julian
 */
public class ResolverReporteSeleccionadoFORM extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(ResolverReporteSeleccionadoFORM.class.getName());
    private ControlForms control;
    private ReporteIncidenteDTO reporteIncidente;
    private byte[] imagenSeleccionada;
    private String mimeType;
    
    /**
     * Creates new form DetallesReporteSeleccionadoFORM
     */
    public ResolverReporteSeleccionadoFORM(ControlForms control) {
        initComponents();
        this.setLocationRelativeTo(null);
        this.control = control;
    }
    public ResolverReporteSeleccionadoFORM(ControlForms control, ReporteIncidenteDTO reporteIncidente) {
        initComponents();
        this.setLocationRelativeTo(null);
        this.control = control;
        this.reporteIncidente = reporteIncidente;
        llenarFolioForm();
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        btnVolverAtras = new javax.swing.JButton();
        lblTitulo = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        txtFolioReporte = new javax.swing.JTextField();
        lblSolucion = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtAreaSolcuion = new javax.swing.JTextArea();
        lblImagen = new javax.swing.JLabel();
        lblLugarImagen = new javax.swing.JLabel();
        btnResolverReporte = new javax.swing.JButton();
        btnSeleccionarImagen = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(18, 18, 18));

        btnVolverAtras.setBackground(new java.awt.Color(255, 0, 51));
        btnVolverAtras.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnVolverAtras.setForeground(new java.awt.Color(255, 255, 255));
        btnVolverAtras.setText("<- Atras");
        btnVolverAtras.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        btnVolverAtras.addActionListener(this::btnVolverAtrasActionPerformed);

        lblTitulo.setFont(new java.awt.Font("Segoe UI", 3, 34)); // NOI18N
        lblTitulo.setForeground(new java.awt.Color(255, 255, 255));
        lblTitulo.setText("GymFit- Buzón Reportes Quejas/Sugerencias");

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Folio: ");

        txtFolioReporte.setEditable(false);
        txtFolioReporte.setBackground(new java.awt.Color(255, 255, 255));
        txtFolioReporte.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        txtFolioReporte.setForeground(new java.awt.Color(0, 0, 0));

        lblSolucion.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        lblSolucion.setForeground(new java.awt.Color(255, 255, 255));
        lblSolucion.setText("Solución:");

        txtAreaSolcuion.setBackground(new java.awt.Color(255, 255, 255));
        txtAreaSolcuion.setColumns(20);
        txtAreaSolcuion.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        txtAreaSolcuion.setForeground(new java.awt.Color(0, 0, 0));
        txtAreaSolcuion.setLineWrap(true);
        txtAreaSolcuion.setRows(5);
        txtAreaSolcuion.setWrapStyleWord(true);
        jScrollPane1.setViewportView(txtAreaSolcuion);

        lblImagen.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        lblImagen.setForeground(new java.awt.Color(255, 255, 255));
        lblImagen.setText("Imagen: ");

        btnResolverReporte.setBackground(new java.awt.Color(255, 0, 51));
        btnResolverReporte.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnResolverReporte.setForeground(new java.awt.Color(255, 255, 255));
        btnResolverReporte.setText("Resolver Reporte");
        btnResolverReporte.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        btnResolverReporte.addActionListener(this::btnResolverReporteActionPerformed);

        btnSeleccionarImagen.setBackground(new java.awt.Color(102, 102, 102));
        btnSeleccionarImagen.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnSeleccionarImagen.setForeground(new java.awt.Color(255, 255, 255));
        btnSeleccionarImagen.setText("Seleccionar Imagen");
        btnSeleccionarImagen.setToolTipText("");
        btnSeleccionarImagen.addActionListener(this::btnSeleccionarImagenActionPerformed);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(btnVolverAtras, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addComponent(lblTitulo)
                .addGap(0, 44, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(188, 188, 188)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblSolucion)
                    .addComponent(jLabel1)
                    .addComponent(lblImagen))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtFolioReporte, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblLugarImagen, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane1))
                .addGap(257, 257, 257))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(btnResolverReporte, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(330, 330, 330))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(btnSeleccionarImagen)
                        .addGap(326, 326, 326))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lblTitulo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnVolverAtras, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(28, 28, 28)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtFolioReporte, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblSolucion))
                .addGap(18, 18, 18)
                .addComponent(btnSeleccionarImagen)
                .addGap(12, 12, 12)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(lblImagen)
                        .addGap(0, 107, Short.MAX_VALUE))
                    .addComponent(lblLugarImagen, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addComponent(btnResolverReporte, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnVolverAtrasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVolverAtrasActionPerformed
        control.navegarDetallesReporteSeleccionadoForm(reporteIncidente);
        this.dispose();
    }//GEN-LAST:event_btnVolverAtrasActionPerformed

    private void btnResolverReporteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnResolverReporteActionPerformed
        boolean generado = resolverReporteIncidente();
        if(generado){
           control.navegarReportesQuejasClientes();
            this.dispose(); 
        }
    }//GEN-LAST:event_btnResolverReporteActionPerformed

    private void btnSeleccionarImagenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSeleccionarImagenActionPerformed
        seleccionarImagen();
    }//GEN-LAST:event_btnSeleccionarImagenActionPerformed
    
    private void seleccionarImagen(){
        try {
            JFileChooser selector = new JFileChooser();
            FileNameExtensionFilter filtro = new FileNameExtensionFilter("Imágenes JPG y PNG", "jpg", "jpeg", "png");
            selector.setFileFilter(filtro);
            int resultado = selector.showOpenDialog(this);

            if (resultado == JFileChooser.APPROVE_OPTION) {
            
                File archivo = selector.getSelectedFile();
                this.imagenSeleccionada = Files.readAllBytes(archivo.toPath());
                this.mimeType = Files.probeContentType(archivo.toPath());
                
                ImageIcon icono = new ImageIcon(this.imagenSeleccionada);
                Image imagenEscalada = icono.getImage().getScaledInstance(
                            lblLugarImagen.getWidth(),
                            lblLugarImagen.getHeight(),
                            Image.SCALE_SMOOTH
                );

                lblLugarImagen.setIcon(new ImageIcon(imagenEscalada));
            }
        }catch (IOException ex) {
            JOptionPane.showMessageDialog(this, "Error al leer la imagen.");
        }
    }
    
    private boolean resolverReporteIncidente(){
        try {
            String folio = reporteIncidente.folio();
            String solucion = txtAreaSolcuion.getText();
            ImagenDTO imagen = null;
            if (this.imagenSeleccionada != null) {
                imagen = new ImagenDTO(this.imagenSeleccionada, null, this.mimeType);
            }
            AtenderReporteDTO reporteAtendido = new AtenderReporteDTO(
                    folio, solucion, imagen
            );
            ReporteAtencionGeneradoDTO reporteGenerado = control.atenderReporteIncidente(reporteAtendido);
            return reporteGenerado != null;
        } catch (NegocioException ex) {
            JOptionPane.showMessageDialog(this, "Error al generar el reporte de incidente. " + ex.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
            return false;
        }
    }
    
    private void llenarFolioForm(){
        txtFolioReporte.setText(reporteIncidente.folio());
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnResolverReporte;
    private javax.swing.JButton btnSeleccionarImagen;
    private javax.swing.JButton btnVolverAtras;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblImagen;
    private javax.swing.JLabel lblLugarImagen;
    private javax.swing.JLabel lblSolucion;
    private javax.swing.JLabel lblTitulo;
    private javax.swing.JTextArea txtAreaSolcuion;
    private javax.swing.JTextField txtFolioReporte;
    // End of variables declaration//GEN-END:variables
}
